apiVersion: v1
kind: Service
metadata:
  name: data-manager
  labels: 
    app: i40-aas
    service: data-manager
spec:
  ports:
  - targetPort: 4000
    port: 80
    protocol: TCP
    name: http
  selector:
    app: i40-aas
    service: data-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-manager
  labels: 
    app: i40-aas
    service: data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: data-manager
  template: 
    metadata:
      labels:
        app: i40-aas
        service: data-manager
    spec:
      containers:
      - name: service
        image: i40aas.azurecr.io/i40-aas-data-manager@SHA-PLACEHOLDER
        ports: 
        - containerPort: 4000
        env:
        - name: ADAPTER_REG_URL
          value: "http://adapter-registry:80/adapters"
        - name: ADAPTER_REG_USER
          value: "admin"
        - name: ADAPTER_REG_PASS
          value: "admin"
