apiVersion: v1
kind: Service
metadata:
  name: adapter-registry
  labels: 
    app: i40-aas
    service: adapter-registry
spec:
  ports:
  - targetPort: 4500
    port: 80
    protocol: TCP
    name: http
  selector:
    app: i40-aas
    service: adapter-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adapter-registry
  labels: 
    app: i40-aas
    service: adapter-registry
spec:
  selector:
    matchLabels:
      app: i40-aas
      service: adapter-registry
  template: 
    metadata:
      labels:
        app: i40-aas
        service: adapter-registry
    spec:
      containers:
      - name: adapter-registry
        image: i40aas.azurecr.io/i40-aas-adapter-registry@SHA-PLACEHOLDER
        ports: 
        - containerPort: 4500
        env:
        - name: ADAPTER_REG_USER
          value: "admin"
        - name: ADAPTER_REG_PASS
          value: "admin"
        - name: AIN_ADAPTER_ID
          value: "storage-adapter-ain"
        - name: MONGO_ADAPTER_ID
          value: "storage-adapter-mongodb"
        - name: AIN_ADAPTER_URL
          value: "http://storage-adapter-ain:80/submodels"
        - name: MONGO_ADAPTER_URL
          value: "http://storage-adapter-mongodb:80/submodels"
        - name: AIN_ADAPTER_SUBMODEL_ID
          value: "opc-ua-devices"
        - name: MONGO_ADAPTER_SUBMODEL_ID
          value: "opc-ua-devices"
        - name: REGISTRY_ADMIN_USER
          value: "admin"
        - name: REGISTRY_ADMIN_PASSWORD
          value: "admin"
