---
apiVersion: v1
kind: Service
metadata:
  name: https-endpoint-egress
  labels: 
    app: i40-aas
    service: https-endpoint-egress
spec:
#  type: LoadBalancer
  ports:
    - targetPort: 3000
      port: 80
      protocol: TCP
      name: http
  selector:
    app: i40-aas
    service: https-endpoint-egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-endpoint-egress
  labels: 
    app: i40-aas
    service: https-endpoint-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i40-aas
      service: https-endpoint-egress
  template: 
    metadata:
      labels:
        app: i40-aas
        service: https-endpoint-egress
    spec:
      containers:
        - name: service
          image: i40aas.azurecr.io/i40-aas-https-endpoint-egress@SHA-PLACEHOLDER
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: registry-postgres
            - configMapRef:
                name: service-addresses
            - configMapRef:
                name: rabbitmq
            - secretRef:
                name: rabbitmq
---
